sudo: required

services:
  - docker

before_install:
  - docker build -t yuriiknowsjava/multi-client:test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yuriiknowsjava/multi-client:test npm run test -- --coverage

after_success:
  # build images
  - docker build -t yuriiknowsjava/multi-client ./client
  - docker build -t yuriiknowsjava/multi-nginx ./nginx
  - docker build -t yuriiknowsjava/multi-server ./server
  - docker build -t yuriiknowsjava/multi-worker ./worker

  # Log into the docker CLI and push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yuriiknowsjava/multi-client
  - docker push yuriiknowsjava/multi-nginx
  - docker push yuriiknowsjava/multi-server
  - docker push yuriiknowsjava/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env # elasticbeanstalk env name
  bucket_name: elasticbeanstalk-us-east-2-695228135251 # AWS s3 name
  bucket_path: multi-docker # folder in s3 
  on:
    branch: main

  # Env variables
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
